### ISSUE TITLE
Adding new app misspell

### ISSUE THREAD

**Issue by vmunozrivera** [Mitchell-Mirano/kamaqi#6]
When you add a new app the last letter you write is replace by the letter "s" and included in 30 places between the 3 app files (models.py, crud.py and router.py). 

Example: if my new app is called 'nuevo' this is generated as 'nuevs' or 'nuev'. 

![image](https://github.com/Mitchell-Mirano/kamaqi/assets/35176705/95b8105d-37b0-44a3-b2e0-fe9655131fb5)

**Comment by Mitchell-Mirano** [comment]
Hello! @vmunozrivera Thanks for reporting this issue, I'll work to fix it.

- By default, kamaqi waits for application names to be plural, perhaps that is the problem.

**Comment by vmunozrivera** [comment]
Hi @Mitchell-Mirano, you are right, if you create the app using plural in works fine. A solution for my issue could be to add the 'S' or plural version of the word if I write it on singular. Or maybe ask for the plural of the name explicitly. Anyways, Thank you for the fast response. I can use it like that for now.

**Comment by Mitchell-Mirano** [comment]
I added a condition that notify when an app name is not in plural form, please test it. Review the develop branch

**Comment by vmunozrivera** [comment]
it shows the following error: 
![image](https://github.com/Mitchell-Mirano/kamaqi/assets/35176705/c1617261-e54d-4d62-bc28-5e88391ca245)

**Comment by vmunozrivera** [comment]
I create a pull request with the indent fixed, with you change it works as you said, it notify the user to create the app in plural.

**Comment by Mitchell-Mirano** [comment]
<img width="413" alt="image" src="https://github.com/Mitchell-Mirano/kamaqi/assets/67351445/93b75e90-0f13-4c2f-b1e8-7c7629d3bdaf">

According to standard the correct change is indent the first if.

**Comment by Mitchell-Mirano** [comment]
Your changes were added to the main branch and compiled for upload to PyPI
