### ISSUE TITLE
Error creating new project on Windows

### ISSUE THREAD

**Issue by vmunozrivera** [Mitchell-Mirano/kamaqi#7]
When execute "kamaqi start project hola_mundo" it throws an error probably because in Window OS it need the openssl installed.

![image](https://github.com/Mitchell-Mirano/kamaqi/assets/35176705/f8dfe146-cf92-43ff-834f-f63818caa22d)

**Comment by vmunozrivera** [comment]
Possible fix:
Use the secret lib for create an hex token. I can make a pull request to a separate branch for testing. It works in my local.
![image](https://github.com/Mitchell-Mirano/kamaqi/assets/35176705/f191b3a1-f6a3-4b68-990f-28b140fb0b3d)

**Comment by Mitchell-Mirano** [comment]
Great! Make a pull request please. Thanks for helping on this project.

**Comment by vmunozrivera** [comment]
Solved in release 0.2.7
